spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_URI}/?retryWrites=true&w=majority
      database: ${MONGO_DB}
      uuid-representation: standard
mongock:
  migration-scan-package:
    - be.leanderonline.cscg.datamigration